"""
ArtistApplet - legacy compatibility layer for artist nodes.

Image generation is now routed through the universal Image Gen node.
"""
import logging
import os
from typing import Any, Dict

from apps.orchestrator.main import AppletMessage, BaseApplet, ImageGenNodeApplet

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("artist-applet")

MOCK_IMAGE = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="


class ArtistApplet(BaseApplet):
    """
    Legacy artist applet wrapper backed by the universal image node.

    Capabilities:
    - Image generation from text descriptions
    - Style transfer
    - Visual creation
    """

    VERSION = "1.0.0"
    CAPABILITIES = ["image-generation", "text-to-image", "visual-creation", "image-node-compatible"]

    def __init__(self):
        self.stability_api_key = os.environ.get("STABILITY_API_KEY")
        self.openai_api_key = os.environ.get("OPENAI_API_KEY")
        if not (self.stability_api_key or self.openai_api_key):
            logger.error(
                "Neither STABILITY_API_KEY nor OPENAI_API_KEY environment variables are set. "
                "ArtistApplet cannot function without at least one."
            )
            raise RuntimeError(
                "At least one of STABILITY_API_KEY or OPENAI_API_KEY environment variables is required for ArtistApplet. "
                "Please set before starting the app."
            )
        self._image_applet = ImageGenNodeApplet()

    async def on_message(self, message: AppletMessage) -> AppletMessage:
        logger.info("Artist Applet received message")

        prompt = self._extract_prompt(message.content)
        context = message.context if isinstance(message.context, dict) else {}
        generator = context.get("image_generator", "stability")
        style = context.get("style", "photorealistic")

        image_data, generator_used = await self._generate_image(prompt, generator, style)

        return AppletMessage(
            content={"image": image_data, "prompt": prompt, "generator": generator_used},
            context={**context},
            metadata={"applet": "artist", "generator": generator_used, "migrated_to": "image"},
        )

    def _extract_prompt(self, content: Any) -> str:
        if isinstance(content, str):
            return content
        if isinstance(content, dict):
            if isinstance(content.get("prompt"), str):
                return content["prompt"]
            if isinstance(content.get("text"), str):
                return content["text"]
        return "A beautiful landscape with mountains and a lake."

    async def _generate_image(self, prompt: str, generator: str, style: str) -> tuple[str, str]:
        if not (self.stability_api_key or self.openai_api_key):
            return MOCK_IMAGE, "mock"

        if generator.lower() == "stability" and self.stability_api_key:
            try:
                return await self._call_stability_api(prompt, style), "stability"
            except Exception as exc:
                logger.error(f"Error with Stability API: {exc}, falling back to OpenAI")
                generator = "openai"

        if generator.lower() == "openai" and self.openai_api_key:
            try:
                return await self._call_openai_api(prompt, style), "openai"
            except Exception as exc:
                logger.error(f"Error with OpenAI API: {exc}")
                return MOCK_IMAGE, "error"

        return MOCK_IMAGE, "mock"

    async def _call_stability_api(self, prompt: str, style: str) -> str:
        config: Dict[str, Any] = {
            "provider": "stability",
            "model": "stable-diffusion-xl-1024-v1-0",
            "style": style,
            "size": "1024x1024",
            "n": 1,
            "response_format": "b64_json",
            "api_key": self.stability_api_key,
        }
        message = AppletMessage(
            content={"prompt": prompt},
            context={"image_config": config},
            metadata={"image_config": config},
        )
        response = await self._image_applet.on_message(message)
        image = self._extract_image(response)
        if image:
            return image
        raise Exception("No image generated by Stability API")

    async def _call_openai_api(self, prompt: str, style: str) -> str:
        config: Dict[str, Any] = {
            "provider": "openai",
            "model": "dall-e-3",
            "style": style,
            "size": "1024x1024",
            "quality": "standard",
            "n": 1,
            "response_format": "b64_json",
            "api_key": self.openai_api_key,
        }
        message = AppletMessage(
            content={"prompt": prompt},
            context={"image_config": config},
            metadata={"image_config": config},
        )
        response = await self._image_applet.on_message(message)
        image = self._extract_image(response)
        if image:
            return image
        raise Exception("No image generated by OpenAI API")

    def _extract_image(self, response: AppletMessage) -> str:
        if response.metadata.get("status") == "error":
            raise Exception(str(response.content))
        if not isinstance(response.content, dict):
            return ""
        image = response.content.get("image")
        if isinstance(image, str):
            return image
        images = response.content.get("images")
        if isinstance(images, list) and images and isinstance(images[0], str):
            return images[0]
        return ""


if __name__ == "__main__":
    import asyncio

    async def test_artist():
        applet = ArtistApplet()
        message = AppletMessage(
            content="A futuristic city with flying cars and neon lights",
            context={},
            metadata={},
        )
        response = await applet.on_message(message)
        print(f"Generated image with {response.content['generator']}")

    asyncio.run(test_artist())
