"""Create initial schema

Revision ID: 3201bb1d2a40
Revises: 81751dea8da7
Create Date: 2025-06-05 15:50:37.752774

"""
from collections.abc import Sequence



# revision identifiers, used by Alembic.
revision: str = '3201bb1d2a40'
down_revision: str | None = '81751dea8da7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
