"""
WriterApplet - legacy compatibility layer for writer nodes.

Writer generation is now routed through the universal LLM node using the
OpenAI/gpt-4o preset.
"""
import logging
import os
from typing import Any, Dict

from apps.orchestrator.main import AppletMessage, BaseApplet, LLMNodeApplet

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("writer-applet")


DEFAULT_SYSTEM_PROMPT = (
    "You are a helpful AI assistant that generates high-quality, creative text."
)


class WriterApplet(BaseApplet):
    """
    Legacy writer applet wrapper backed by the universal LLM node.

    Capabilities:
    - Text generation from prompts
    - Content creation
    - Summarization
    """

    VERSION = "1.0.0"
    CAPABILITIES = ["text-generation", "summarization", "content-creation", "llm-node-compatible"]

    def __init__(self):
        self.api_key = os.environ.get("OPENAI_API_KEY")
        if not self.api_key:
            logger.error(
                "OPENAI_API_KEY environment variable is missing. WriterApplet cannot function without it."
            )
            raise RuntimeError(
                "OPENAI_API_KEY environment variable is required for WriterApplet. Please set it before starting the app."
            )
        self._llm_applet = LLMNodeApplet()

    async def on_message(self, message: AppletMessage) -> AppletMessage:
        logger.info("Writer Applet received message")

        prompt = self._extract_prompt(message.content)
        context = message.context if isinstance(message.context, dict) else {}
        system_prompt = context.get("system_prompt", DEFAULT_SYSTEM_PROMPT)

        generated_text = await self._generate_text(prompt, system_prompt)

        return AppletMessage(
            content=generated_text,
            context={**context},
            metadata={
                "applet": "writer",
                "provider": "openai",
                "model": "gpt-4o",
                "migrated_to": "llm",
            },
        )

    def _extract_prompt(self, content: Any) -> str:
        if isinstance(content, str):
            return content
        if isinstance(content, dict):
            if isinstance(content.get("prompt"), str):
                return content["prompt"]
            if isinstance(content.get("text"), str):
                return content["text"]
        return "Please provide some information to work with."

    async def _generate_text(self, prompt: str, system_prompt: str) -> str:
        if not self.api_key:
            return f"This is a mock response for: {prompt}. In the real app, this would be generated by gpt-4o."

        llm_config: Dict[str, Any] = {
            "label": "Writer",
            "provider": "openai",
            "model": "gpt-4o",
            "system_prompt": system_prompt,
            "temperature": 0.7,
            "max_tokens": 1000,
            "api_key": self.api_key,
            "stream": False,
        }

        llm_message = AppletMessage(
            content={"prompt": prompt},
            context={"llm_config": llm_config},
            metadata={"llm_config": llm_config},
        )

        try:
            response = await self._llm_applet.on_message(llm_message)
        except Exception as exc:
            logger.error(f"Error calling LLM node from WriterApplet: {exc}")
            return f"Error generating text: {str(exc)}"

        if response.metadata.get("status") == "error":
            return f"Error generating text: {response.content}"

        if not isinstance(response.content, str):
            logger.error("LLM node returned non-string content for WriterApplet")
            return "Error generating text: Invalid response format from LLM provider"

        return response.content


if __name__ == "__main__":
    import asyncio

    async def test_writer():
        applet = WriterApplet()
        message = AppletMessage(
            content="Write a short poem about AI and creativity",
            context={},
            metadata={},
        )
        response = await applet.on_message(message)
        print(response.content)

    asyncio.run(test_writer())
